### ISSUE TITLE
Models not recognized.

### ISSUE THREAD

**Issue by Lestat1986** [natanjunges/stable-diffusion-webui-stable-horde#10]
Been a while since I last used the extension so might be some changes that I am not aware off.

Every model I try to load in the web interface gives me the error as example:
md5sum for Deliberate.ckpt is 65621076b884a0debcae553aa142e935 but it's not supported by StableHorde

Steps taken:
Install A1111 and run it - confirmed working
Install the stable horde extension and restart

Now I tried 2 different way to get the correct model.

Try 1.
Downloading the correct one from the file here:
https://github.com/Haidra-Org/AI-Horde-image-model-reference/blob/main/stable_diffusion.json
Which lead me to https://huggingface.co/Airic/mirrors/resolve/main/Deliberate.ckpt

Complains about not supported.

Try 2. 
Installed the original horde worker bridge from: https://github.com/Haidra-Org/AI-Horde-Worker
Let it download the deliberate model and let the worker run a while (which works perfectly fine)
Copied the ckpt file to my models folder and ran A1111 again with the same result that the model is not supported.

**Comment by natanjunges** [comment]
This extension is not a worker, but a client instead. It doesn't load any models, so the error message you are getting must come from another extension.
