### ISSUE TITLE
Awesome...Some Clarification

### ISSUE THREAD

**Issue by infocyde** [natanjunges/stable-diffusion-webui-stable-horde#2]
First, thanks for this natanjungles.  On my 8 gig vram constrained laptop using SD with Stable Horde will open up new doors, I appreciate this script.

Just a few points of clarity for documentation...

The style.css file...do I append that at the end of the existing style.css file in my room automatic1111/stable diffisuion web ui folder?  And if so, if I have git pull in my webui-user.bat file, will any changes made by the automatic1111 admins to that style.css file overwrite what I have locally?  Same with the script files.

Noob question, thank you!

**Comment by natanjunges** [comment]
I have a 2GB VRAM laptop myself, and Stable Horde really makes things easier. To install this extension, like any other, just do as instructed [here](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Extensions). From the root folder of the Web UI, run:
```bash
git clone https://github.com/natanjunges/stable-diffusion-webui-stable-horde extensions/stable-horde
```
