### ISSUE TITLE
AttributeError: type object 'FakeModel' has no attribute 'sd_checkpoint_info'

### ISSUE THREAD

**Issue by leohu1** [natanjunges/stable-diffusion-webui-stable-horde#3]
AttributeError: type object 'FakeModel' has no attribute 'sd_checkpoint_info'

**Comment by leohu1** [comment]
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 0b8911d883118daa54f7735c5b753b5575d9f943

diffusers version 0.10.2 installed.
transformers version 4.25.1 installed.
torch version 1.13.1+cu117 installed.
torchvision version 0.14.1+cu117 installed.

Error completing request
Arguments: ('flat color, (masterpiece:1.5), (best quality:1.5), amazing, beautiful detailed, extremely detailed wallpaper, extremely detailed CG unity 8k wallpaper, extremely delicate and beautiful, finely detailed, extremely detailed wallpaper, fantasy, official art, detailed background, (beautiful detailed shadow: 1.5, cinematic lighting, backlight), [((symmetrical geometry, science fiction: 1.5, vacuumpunk: 1.5, 1960s (style): 1.5, ArtDeco), (control room, nixie tubes: 1.8, machines, silver, metallochrome, wires, vacuum tubes, old computers, simple screens))::0.75], [((solo: 1.5), (1 girl), (teenage girl, cute, extremely detailed eyes and face, clear eyes, clear face, white medium hair, red eyes, white lab coat: 1.5, hands in pocket: 1.5, black shirt: 1.5, black trousers, looking at viewer, light smile: 1.3, cropped torso: 1.8, medium close up: 1.5, waist shot: 1.5), depth of field): 0.25]', 'multiple breasts, (mutated hands and fingers: 1.5), (long body: 1.3), (mutation, poorly drawn: 1.2) , black-white, bad anatomy, liquid body, liquid tongue, disfigured, malformed, mutated, anatomical nonsense, error, malformed hands, long neck, blurred, lowres, bad anatomy, bad proportions, bad shadow, uncoordinated body, unnatural body, mutated breasts, huge haunch, huge thighs, huge calf, mutated ears, text, ui, error, missing fingers, missing limb, cropped, watermark, username, blurry, JPEG artifacts, signature, 3D, malformed feet, bad gloves, bad cum, bad hairs, big muscles, ugly, bad face, obesity, worst quality, low quality, normal quality, duplicate, morbid, mutilated, fused tentacles, QR code, bar code, censored', 'None', 'None', 100, 1, False, False, 1, 1, 15, 1174191459.0, -1.0, 0, 0, 0, False, 640, 1024, False, 0.7, 2, 'Latent', 0, 0, 0, 7, 0, 0, 0, 0, 0.25, '', '', False, False, False, False, '', 1, '', 0, '', True, False, False, '', False, False, False, False, 'Auto', 0.5, 1, 'Anything Diffusion (17)', False, False, 1, 'None', 'None', 'None') {}
Traceback (most recent call last):
  File "G:\stable-diffusion-webui\modules\call_queue.py", line 45, in f
    res = list(func(*args, **kwargs))
  File "G:\stable-diffusion-webui\modules\call_queue.py", line 28, in f
    res = func(*args, **kwargs)
  File "G:\stable-diffusion-webui\modules\txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "G:\stable-diffusion-webui\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-stable-horde\scripts\main.py", line 181, in run
    return self.process_images(p, model, nsfw, shared_laion, int(seed_variation), post_processing)
  File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-stable-horde\scripts\main.py", line 202, in process_images
    res = self.process_images_inner(p, model, nsfw, shared_laion, seed_variation, post_processing)
  File "G:\stable-diffusion-webui\extensions\stable-diffusion-webui-stable-horde\scripts\main.py", line 253, in process_images_inner
    file.write(processed.infotext(p, 0))
  File "G:\stable-diffusion-webui\modules\processing.py", line 325, in infotext
    return create_infotext(p, self.all_prompts, self.all_seeds, self.all_subseeds, comments=[], position_in_batch=index % self.batch_size, iteration=index // self.batch_size)
  File "G:\stable-diffusion-webui\modules\processing.py", line 438, in create_infotext
    "Model": (None if not opts.add_model_name_to_info or not shared.sd_model.sd_checkpoint_info.model_name else shared.sd_model.sd_checkpoint_info.model_name.replace(',', '').replace(':', '')),
AttributeError: type object 'FakeModel' has no attribute 'sd_checkpoint_info'

**Comment by natanjunges** [comment]
Fixed by https://github.com/natanjunges/stable-diffusion-webui-stable-horde/commit/97b74e13fde5a03687fd61126ac9ac4114dd8e82.
