### ISSUE TITLE
Q: What does this mean? It's a job of 16 with 15 finished and now it's doing nothing.

### ISSUE THREAD

**Issue by axemaster** [natanjunges/stable-diffusion-webui-stable-horde#8]
Pending: 0 - Processing: 0 - Finished: 15 - Restarted: 1 - Failed: 0
Queue Position: 0

Why isn't the "restarted" job processing? If that's the problem. it's been like this ~ 30 minutes.

**Comment by natanjunges** [comment]
This is an issue with the horde, not with this extension. Please contact the [AI horde](https://github.com/db0/AI-Horde) team.
