### ISSUE TITLE
Can you explain some of these options?

### ISSUE THREAD

**Issue by curtmgray** [natanjunges/stable-diffusion-webui-stable-horde#9]
Thanks for providing this plugin! Can you explain what these options do?

![image](https://github.com/natanjunges/stable-diffusion-webui-stable-horde/assets/21285187/b6ffa8a2-174c-4aad-bc28-cdf94105f022)

For example...
For model is it random for the one time I press the generate button? Or is it randomly picking for each image generated in a batch?

Is the NSFW button forcing NSFW images? Is it allowing NSFW images?

Seed variation? I have no idea what this is doing, is it randomizing the seed or like....what?

Various post processing options...I imagine these are running in order selected right?

**Comment by natanjunges** [comment]
- I'm not so sure, as it is a behavior of the horde and not of this extension, but I would guess it chooses a random model and applies it to an entire batch;
- The NSFW option allows NSFW generations, and disabling it makes NSFW generations get censored;
- The seed variation specifies how far apart the seeds for each individual generation are in a batch;
- Yes, the post processing stages are applied in the specified order.
